---
title: "Simulations log"
output: github_document
---

This directory contains all scripts used to simulate systematic reviews. 
Note that the files resulting from this simulation are enormous (over 500GB in total), therefore they cannot be stored on GitHub. Instead, those files are published on the Open Science Framework, divided over 2 .. 

- `scripts` -  contains all scripts run on the Cartesius supercomputer. The `log.Rmd` file tracks when all these scripts were executed and connects them to a jobID on Cartesius (just for documentation).
- `config` - contains the hyperparameters for every model-dataset combination. These files are called upon in the simulation command. 

If you want to run a simulation locally, for example the NB + TF-IDF model on the nudging run the following in your bash terminal:

```{bash, eval = FALSE}

```

The simulation will output one or more `.h5` files (depending on the number of trials you choose). Please refer to the `results` folder in the root directory of this repository for a demonstration of how to analyze the resulting files. 